Implemented `date`
proh14/canoutils pull request #38
Opened 2024-04-21 13:25 UTC by Eike-Flath

I implemented `date` as described by the [POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/date.html).
I did implement support for changing the system time, though my implementation is platform-specific as far as I know. It works on my machine :) 
I did not implement any features that are not described in the POSIX standard.

2024-04-21 18:03 UTC, Sigmanificient requested changes

2024-04-21 18:03 UTC, Sigmanificient commented on src/date/date.c
> +  char *buf = malloc(cap);
missing malloc/realloc call checks

2024-04-23 05:21 UTC, proh14 commented
hello thanks for your contribution! please also add `--help` `--version` flags + some of the gnu flags

2024-04-28 17:04 UTC, Eike-Flath commented
@proh14 I now added `--help` as well as the GNU flags `--iso-8601`, `--rfc-3339`, and `--rfc-email` (as well as their short option equivalents). I also added support for the GNU format specifiers `%N` and `%:z`.
Are there any other GNU features you would like to see implemented?

2024-04-28 17:37 UTC, Sigmanificient requested changes

2024-04-28 17:37 UTC, Sigmanificient commented on src/date/date.c
> +#define _POSIX_C_SOURCE 200112L // for setenv
You will need to create your own `setenv`. Fear not, it is simpler than it seems.
Take a look at [glibc implementaion](https://sourceware.org/git/?p=glibc.git;a=blob;f=stdlib/setenv.c;h=e2164371ade896e9b3342754724e5ca381beb64e;hb=HEAD) or [muscl one](https://git.musl-libc.org/cgit/musl/tree/src/env/setenv.c)

2024-04-28 17:37 UTC, Sigmanificient commented on src/date/date.c
> +}
rebase and move to `getopt_long`

2024-04-28 17:37 UTC, Sigmanificient commented on src/date/date.c
> +}
Consider
```suggestion
#define strpre(pre, str) (!strncmp((pre), (str), sizeof (pre) - 1))
```

2025-05-27 07:06 UTC, closed without merging