Implemented cksum
proh14/canoutils pull request #40
Opened 2024-04-21 22:52 UTC by cospplredman

cksum is one of the posix utilities of all time.

2024-04-21 23:07 UTC, Sigmanificient requested changes

2024-04-21 23:07 UTC, Sigmanificient commented on src/cksum/cksum
Please remove the binary file and add it to gitignore list.
Make sure to add your the folder name in `BINS` variable of the global Makefile

2024-04-21 23:07 UTC, Sigmanificient commented on src/cksum/cksum.c
> +#include<stdint.h>
Can you run `clang-format`? This enforce coding style consistency across all sources

2024-04-21 23:07 UTC, Sigmanificient commented on src/cksum/cksum.c
> +	}
missing `fclose`?

2024-04-21 23:08 UTC, Sigmanificient commented
The core logic is a bit cryptic (mostly bit manipulation) so I couldn't tell what happening there

2024-04-22 01:12 UTC, Sigmanificient approved these changes

2024-04-22 02:13 UTC, proh14 commented
hello @cospplredman. thanks for your pr. please test this before we merge it. Also, be sure to provide. if you tasted all the edge cases, mention me so I can merge it. ;)

2024-04-22 02:14 UTC, proh14 approved these changes

2024-04-22 02:42 UTC, cospplredman commented
My testing methodology is as follows: run both my implementation and the gnu implementation on every file in the cksum directory.

```sh
$ ./cksum *
175369053 16296 cksum
1855786587 7 cksum.1
4088649404 2179 cksum.c
1192622583 51 Makefile
197436690 157 test.sh
$ cksum *
175369053 16296 cksum
1855786587 7 cksum.1
4088649404 2179 cksum.c
1192622583 51 Makefile
197436690 157 test.sh
```

the results match as far as i can tell.

One notable difference between this implementation and the gnu implementation is that I do not handle directories, I opt to instead just return EXIT_FAILURE. The reason I prefer to fail is that there isn't a standard C way of checking if something is a directory, so any method of doing so would break me from my (very tasteful) c99 compliance, and cksum is only defined on files anyways.

2024-04-22 08:38 UTC, proh14 requested changes

2024-04-22 08:38 UTC, proh14 commented on src/cksum/cksum.c
> +#include "getopt.h"
Change `getopt.h` to `cgetopt.h`

2024-04-22 08:38 UTC, proh14 commented on src/cksum/cksum.c
> +  while ((opt = getopt(argc, argv, "v")) != -1) {
use getopt_long instead of normal getopt. do `man getopt.3` for more info

2024-04-22 08:38 UTC, proh14 commented on src/cksum/cksum.c
> +    if (file == NULL)
If file cannot be opened print errno. `perror("cksum")`

2024-04-22 08:38 UTC, proh14 commented on src/cksum/cksum.c
> +    case 'v':
add more flags

2024-04-22 08:38 UTC, proh14 commented
also pull the latest changes

2024-04-24 00:07 UTC, proh14 approved these changes
thx ;)

2024-04-24 00:10 UTC, merged